config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :contacts
  resources :registrations
  resources :courses
  resources :courses
  resources :writers
  resources :writers
  resources :writers
  resources :professional_memberships
  resources :medical_educations
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :registrations
  resources :users
  resources :consultations
  resources :vidios
  resources :categories
  resources :articles
  resources :schedules
  resources :doctors
  resources :sliders
  root 'page#index'

  get 'index' =>'page#index' , :as => :home
  get 'about' =>'page#about' , :as => :about
  get 'registration' =>'page#registration' , :as => :registration_page
  get 'consultation' =>'page#consultation' , :as => :consultation_page

  get 'dashboard' =>'dashboard#index', :as => :dashboard
  get 'dr-sapto-adji-h-sp-ot' => 'page#doctor', :as => :single_doctor
  get 'cedera-bahu-yang-sering-terjadi' => 'page#article', :as => :single_article
  get 'chronic-shoulder-instability' => 'page#article', :as => :second_article
  get 'latest-article' => 'page#latest', :as => :latest
  get 'contact-us' => 'page#contact_us', :as => :contact_us


end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base

 has_many :articles

end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many :writers

  has_many :medical_educations, inverse_of: :doctor
  accepts_nested_attributes_for :medical_educations, reject_if: :all_blank, allow_destroy: true

  has_many :professional_memberships, inverse_of: :doctor
  accepts_nested_attributes_for :professional_memberships, reject_if: :all_blank, allow_destroy: true

  has_many :courses, inverse_of: :doctor
  accepts_nested_attributes_for :courses, reject_if: :all_blank, allow_destroy: true
end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :doctor
end

app/models/service.rb
class Service < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/slider.rb
class Slider < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vidio.rb
class Vidio < ActiveRecord::Base
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  belongs_to :doctor
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  layout 'admin', except:[:show]
  # before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title_en, :title_id, :content_id, :content_en, :category_id, :image, :writer_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vidios_helper.rb
module VidiosHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "" } do |f| %>

<% if @article.errors.any? %>
<div class="panel">
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %>
        prohibited this article from being saved:
      </h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>
<div class="row">
  <div class="col-md-9">
    <div class="panel">
      <div class="panel-heading">
        Article
      </div>
      <div class="panel-body">
        <div class="form-group">
          <%= f.label :title_id, "Title in Indonesia", :class => 'control-label ' %>
          <%= f.text_field :title_id, :class => 'form-control' %>
          <%=f.error_span(:title_id) %>
        </div>
        <div class="form-group">
          <%= f.label :content_id, "Content in Indonesia", :class => 'control-label' %>
          <%= f.cktext_area :content_id, :class => 'form-control' %>
          <%=f.error_span(:content_id) %>
        </div>
        <div class="form-group">
          <%= f.label :title_en, "Title in English", :class => 'control-label ' %>
          <%= f.text_field :title_en, :class => 'form-control' %>
          <%=f.error_span(:title_en) %>
        </div>
        <div class="form-group">
          <%= f.label :content_en, "Content in English", :class => 'control-label' %>
          <%= f.cktext_area :content_en, :class => 'form-control' %>
          <%=f.error_span(:content_en) %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel">
      <div class="panel-heading">
        Featured <b>Image</b>
      </div>
      <div class="panel-body">
        <% unless @article.image.file.nil? %>
          <img src="<%= @article.image.url %>" alt="" width="100%">
        <% end %>
        <div class="file-field input-field">
          <div class="btn teal lighten-1">
            <span>Choose</span>
            <%= f.file_field :image %>
          </div>
          <!-- <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div> -->
        </div>
      </div>
    </div>

    <div class="panel">
      <div class="panel-heading">
        Article <b>Category</b>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <%= f.select :category_id, Category.all.map {|s| [s.title_id, s.id ]},{} , id: "basic", style: "width:100%;", :class=>"form-control",
          :placeholder=>"asuss"%>
          <%=f.error_span(:category_id) %>
        </div>
      </div>
    </div>

    <div class="panel">
      <div class="panel-heading">
        Select <b>Writer</b>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <%= f.select :writer_id, Writer.all.map {|s| [s.name, s.id ]},{} , id: "basic", style: "width:100%;", :class=>"form-control",
          :placeholder=>"asuss"%>
          <%=f.error_span(:category_id) %>
        </div>
      </div>
    </div>
    <div class="panel">
      <div class="panel-heading">
        Select <b>Action</b>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <div class="">
            <%= f.submit nil, :class => 'btn btn-primary' %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")), articles_path, :class => 'btn btn-default' %>
          </div>
        </div>

      </div>
    </div>
  </div>

</div>


<% end %>

<script type="text/javascript">
CKEDITOR.replace("article[content_en]");
</script>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<h2>Edit <b><%=t '.title', :default => ['%{model}'], :model => model_class.model_name.human.titleize %></b>  </h2>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="panel">
  <div class="panel-heading" style="display: flex;align-items: center;justify-content: space-between;">
    <h1 style="margin:0;font-weight:500;"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    <%= link_to t('.new', :default => t("helpers.links.new")),new_article_path,:class => 'btn btn-primary' %>
  </div>
  <div class="panel-body">
    <table class="table table-hover table-stripped no-m" id="dataTables">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:title_en) %></th>
          <th><%= model_class.human_attribute_name(:title_id) %></th>
          <th><%= model_class.human_attribute_name(:category_id) %></th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
        <tr>
          <td><%= link_to article.id, article_path(article) %></td>
          <td><%= article.title_en %></td>
          <td><%= article.title_id %></td>
          <td><%= article.category.try(:title)  %></td>
          <td><%=l article.created_at %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_article_path(article), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            article_path(article),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>




<script type="text/javascript">
$(document).ready( function () {
  $('#dataTables').DataTable();
} );
</script>

app/views/articles/new.html.erb
  <h2>Create New <b>Article</b></h2>

<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<section class="vh25">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mt-4 article">
        <h1><%= @article.title_id %></h1>
        <span><%= @article.category.title_id %></span> | <strong class="date"><%= @article.created_at.strftime("%e %B %Y") rescue "-" %></strong>
        <img src="<%= @article.image %>" alt="" class="w-100 mt-2 mb-2">
        <div class="mt-3">
          <%= @article.content_id.html_safe %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="p-3 sticky-top shadow-sm" style=" top:95px;background:white;z-index:8;">
          <h3 style="color:#173958;font-weight:500;">Others Stories</h3>
          <ol class="series pl-3">
            <% Article.where(category_id: @article.category_id).where.not(id: @article.id).limit(5).order(created_at: :desc).each do |x|%>
            <li><a href="<%= article_path(x.id)%>"><%= x.title_id %></a> </li>
            <% end %>
          </ol>



        <hr>

        <h3 style="color:#173958;font-weight:500;">Categories</h3>
        <ol class="series pl-3">
          <% Category.all.each do |x|%>
          <li><a href="<%= category_path(x.id) %>"><%= x.title_id %></a> </li>
          <% end %>
        </ol>
      </div>

      </div>
    </div>
  </div>
</section>