config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :contacts
  resources :registrations
  resources :courses
  resources :courses
  resources :writers
  resources :writers
  resources :writers
  resources :professional_memberships
  resources :medical_educations
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :registrations
  resources :users
  resources :consultations
  resources :vidios
  resources :categories
  resources :articles
  resources :schedules
  resources :doctors
  resources :sliders
  root 'page#index'

  get 'index' =>'page#index' , :as => :home
  get 'about' =>'page#about' , :as => :about
  get 'registration' =>'page#registration' , :as => :registration_page
  get 'consultation' =>'page#consultation' , :as => :consultation_page

  get 'dashboard' =>'dashboard#index', :as => :dashboard
  get 'dr-sapto-adji-h-sp-ot' => 'page#doctor', :as => :single_doctor
  get 'cedera-bahu-yang-sering-terjadi' => 'page#article', :as => :single_article
  get 'chronic-shoulder-instability' => 'page#article', :as => :second_article
  get 'latest-article' => 'page#latest', :as => :latest
  get 'contact-us' => 'page#contact_us', :as => :contact_us


end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base

 has_many :articles

end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many :writers

  has_many :medical_educations, inverse_of: :doctor
  accepts_nested_attributes_for :medical_educations, reject_if: :all_blank, allow_destroy: true

  has_many :professional_memberships, inverse_of: :doctor
  accepts_nested_attributes_for :professional_memberships, reject_if: :all_blank, allow_destroy: true

  has_many :courses, inverse_of: :doctor
  accepts_nested_attributes_for :courses, reject_if: :all_blank, allow_destroy: true
end

app/models/medical_education.rb
class MedicalEducation < ActiveRecord::Base
  belongs_to :doctor
end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :doctor
end

app/models/service.rb
class Service < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/slider.rb
class Slider < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vidio.rb
class Vidio < ActiveRecord::Base
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  belongs_to :doctor
end

app/controllers/medical_educations_controller.rb
class MedicalEducationsController < ApplicationController
  before_action :set_medical_education, only: [:show, :edit, :update, :destroy]

  # GET /medical_educations
  # GET /medical_educations.json
  def index
    @medical_educations = MedicalEducation.all
  end

  # GET /medical_educations/1
  # GET /medical_educations/1.json
  def show
  end

  # GET /medical_educations/new
  def new
    @medical_education = MedicalEducation.new
  end

  # GET /medical_educations/1/edit
  def edit
  end

  # POST /medical_educations
  # POST /medical_educations.json
  def create
    @medical_education = MedicalEducation.new(medical_education_params)

    respond_to do |format|
      if @medical_education.save
        format.html { redirect_to @medical_education, notice: 'Medical education was successfully created.' }
        format.json { render :show, status: :created, location: @medical_education }
      else
        format.html { render :new }
        format.json { render json: @medical_education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_educations/1
  # PATCH/PUT /medical_educations/1.json
  def update
    respond_to do |format|
      if @medical_education.update(medical_education_params)
        format.html { redirect_to @medical_education, notice: 'Medical education was successfully updated.' }
        format.json { render :show, status: :ok, location: @medical_education }
      else
        format.html { render :edit }
        format.json { render json: @medical_education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_educations/1
  # DELETE /medical_educations/1.json
  def destroy
    @medical_education.destroy
    respond_to do |format|
      format.html { redirect_to medical_educations_url, notice: 'Medical education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_education
      @medical_education = MedicalEducation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medical_education_params
      params.require(:medical_education).permit(:title, :doctor_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/medical_educations_helper.rb
module MedicalEducationsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vidios_helper.rb
module VidiosHelper
end

app/views/medical_educations/_form.html.erb
<%= form_for(@medical_education) do |f| %>
  <% if @medical_education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medical_education.errors.count, "error") %> prohibited this medical_education from being saved:</h2>

      <ul>
      <% @medical_education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br>
    <%= f.text_field :doctor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medical_educations/edit.html.erb
<h1>Editing Medical Education</h1>

<%= render 'form' %>

<%= link_to 'Show', @medical_education %> |
<%= link_to 'Back', medical_educations_path %>

app/views/medical_educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Medical Educations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Doctor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_educations.each do |medical_education| %>
      <tr>
        <td><%= medical_education.title %></td>
        <td><%= medical_education.doctor %></td>
        <td><%= link_to 'Show', medical_education %></td>
        <td><%= link_to 'Edit', edit_medical_education_path(medical_education) %></td>
        <td><%= link_to 'Destroy', medical_education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medical education', new_medical_education_path %>

app/views/medical_educations/new.html.erb
<h1>New Medical Education</h1>

<%= render 'form' %>

<%= link_to 'Back', medical_educations_path %>

app/views/medical_educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @medical_education.title %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @medical_education.doctor %>
</p>

<%= link_to 'Edit', edit_medical_education_path(@medical_education) %> |
<%= link_to 'Back', medical_educations_path %>