config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :contacts
  resources :registrations
  resources :courses
  resources :courses
  resources :writers
  resources :writers
  resources :writers
  resources :professional_memberships
  resources :medical_educations
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :registrations
  resources :users
  resources :consultations
  resources :vidios
  resources :categories
  resources :articles
  resources :schedules
  resources :doctors
  resources :sliders
  root 'page#index'

  get 'index' =>'page#index' , :as => :home
  get 'about' =>'page#about' , :as => :about
  get 'registration' =>'page#registration' , :as => :registration_page
  get 'consultation' =>'page#consultation' , :as => :consultation_page

  get 'dashboard' =>'dashboard#index', :as => :dashboard
  get 'dr-sapto-adji-h-sp-ot' => 'page#doctor', :as => :single_doctor
  get 'cedera-bahu-yang-sering-terjadi' => 'page#article', :as => :single_article
  get 'chronic-shoulder-instability' => 'page#article', :as => :second_article
  get 'latest-article' => 'page#latest', :as => :latest
  get 'contact-us' => 'page#contact_us', :as => :contact_us


end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base

 has_many :articles

end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many :writers

  has_many :medical_educations, inverse_of: :doctor
  accepts_nested_attributes_for :medical_educations, reject_if: :all_blank, allow_destroy: true

  has_many :professional_memberships, inverse_of: :doctor
  accepts_nested_attributes_for :professional_memberships, reject_if: :all_blank, allow_destroy: true

  has_many :courses, inverse_of: :doctor
  accepts_nested_attributes_for :courses, reject_if: :all_blank, allow_destroy: true
end

app/models/professional_membership.rb
class ProfessionalMembership < ActiveRecord::Base
  belongs_to :doctor
end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :doctor
end

app/models/service.rb
class Service < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/slider.rb
class Slider < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vidio.rb
class Vidio < ActiveRecord::Base
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  belongs_to :doctor
end

app/controllers/professional_memberships_controller.rb
class ProfessionalMembershipsController < ApplicationController
  before_action :set_professional_membership, only: [:show, :edit, :update, :destroy]

  # GET /professional_memberships
  # GET /professional_memberships.json
  def index
    @professional_memberships = ProfessionalMembership.all
  end

  # GET /professional_memberships/1
  # GET /professional_memberships/1.json
  def show
  end

  # GET /professional_memberships/new
  def new
    @professional_membership = ProfessionalMembership.new
  end

  # GET /professional_memberships/1/edit
  def edit
  end

  # POST /professional_memberships
  # POST /professional_memberships.json
  def create
    @professional_membership = ProfessionalMembership.new(professional_membership_params)

    respond_to do |format|
      if @professional_membership.save
        format.html { redirect_to @professional_membership, notice: 'Professional membership was successfully created.' }
        format.json { render :show, status: :created, location: @professional_membership }
      else
        format.html { render :new }
        format.json { render json: @professional_membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professional_memberships/1
  # PATCH/PUT /professional_memberships/1.json
  def update
    respond_to do |format|
      if @professional_membership.update(professional_membership_params)
        format.html { redirect_to @professional_membership, notice: 'Professional membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @professional_membership }
      else
        format.html { render :edit }
        format.json { render json: @professional_membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professional_memberships/1
  # DELETE /professional_memberships/1.json
  def destroy
    @professional_membership.destroy
    respond_to do |format|
      format.html { redirect_to professional_memberships_url, notice: 'Professional membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional_membership
      @professional_membership = ProfessionalMembership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professional_membership_params
      params.require(:professional_membership).permit(:title, :doctor_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/professional_memberships_helper.rb
module ProfessionalMembershipsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vidios_helper.rb
module VidiosHelper
end

app/views/professional_memberships/_form.html.erb
<%= form_for(@professional_membership) do |f| %>
  <% if @professional_membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professional_membership.errors.count, "error") %> prohibited this professional_membership from being saved:</h2>

      <ul>
      <% @professional_membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br>
    <%= f.text_field :doctor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professional_memberships/edit.html.erb
<h1>Editing Professional Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @professional_membership %> |
<%= link_to 'Back', professional_memberships_path %>

app/views/professional_memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Professional Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Doctor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professional_memberships.each do |professional_membership| %>
      <tr>
        <td><%= professional_membership.title %></td>
        <td><%= professional_membership.doctor %></td>
        <td><%= link_to 'Show', professional_membership %></td>
        <td><%= link_to 'Edit', edit_professional_membership_path(professional_membership) %></td>
        <td><%= link_to 'Destroy', professional_membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professional membership', new_professional_membership_path %>

app/views/professional_memberships/new.html.erb
<h1>New Professional Membership</h1>

<%= render 'form' %>

<%= link_to 'Back', professional_memberships_path %>

app/views/professional_memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @professional_membership.title %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @professional_membership.doctor %>
</p>

<%= link_to 'Edit', edit_professional_membership_path(@professional_membership) %> |
<%= link_to 'Back', professional_memberships_path %>