config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :contacts
  resources :registrations
  resources :courses
  resources :courses
  resources :writers
  resources :writers
  resources :writers
  resources :professional_memberships
  resources :medical_educations
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :registrations
  resources :users
  resources :consultations
  resources :vidios
  resources :categories
  resources :articles
  resources :schedules
  resources :doctors
  resources :sliders
  root 'page#index'

  get 'index' =>'page#index' , :as => :home
  get 'about' =>'page#about' , :as => :about
  get 'registration' =>'page#registration' , :as => :registration_page
  get 'consultation' =>'page#consultation' , :as => :consultation_page

  get 'dashboard' =>'dashboard#index', :as => :dashboard
  get 'dr-sapto-adji-h-sp-ot' => 'page#doctor', :as => :single_doctor
  get 'cedera-bahu-yang-sering-terjadi' => 'page#article', :as => :single_article
  get 'chronic-shoulder-instability' => 'page#article', :as => :second_article
  get 'latest-article' => 'page#latest', :as => :latest
  get 'contact-us' => 'page#contact_us', :as => :contact_us


end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base

 has_many :articles

end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many :writers

  has_many :medical_educations, inverse_of: :doctor
  accepts_nested_attributes_for :medical_educations, reject_if: :all_blank, allow_destroy: true

  has_many :professional_memberships, inverse_of: :doctor
  accepts_nested_attributes_for :professional_memberships, reject_if: :all_blank, allow_destroy: true

  has_many :courses, inverse_of: :doctor
  accepts_nested_attributes_for :courses, reject_if: :all_blank, allow_destroy: true
end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :doctor
end

app/models/service.rb
class Service < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/slider.rb
class Slider < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vidio.rb
class Vidio < ActiveRecord::Base
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  belongs_to :doctor
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout 'admin', except:[:show]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title_en, :title_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vidios_helper.rb
module VidiosHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "" } do |f| %>

<% if @category.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>
<div class="panel">
  <div class="panel-heading">
    Setup <b>Category</b>
  </div>
  <div class="panel-body">
    <div class="form-horizontal category">
      <div class="form-group">
        <%= f.label :title_en, "Title in English", :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :title_en, :class => 'form-control' %>
        </div>
        <%=f.error_span(:title_en) %>
      </div>
      <div class="form-group">
        <%= f.label :title_id, "Title in Indonesia", :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :title_id, :class => 'form-control' %>
        </div>
        <%=f.error_span(:title_id) %>
      </div>
    </div>
  </div>
</div>


<div class="panel">
  <div class="panel-heading">
    Select <b>Action</b>
  </div>
  <div class="panel-body">
    <div class="form-group">
      <div class="">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-default' %>
      </div>
    </div>

  </div>
</div>

<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<h2>Edit <b><%=t '.title', :default => ['%{model}'], :model => model_class.model_name.human.titleize %></b>  </h2>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="panel">
  <div class="panel-heading" style="display: flex;align-items: center;justify-content: space-between;">
    <h1 style="margin:0;font-weight:500;"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    <%= link_to t('.new', :default => t("helpers.links.new")),new_category_path,:class => 'btn btn-primary' %>
  </div>
  <div class="panel-body">
    <table class="table table-hover table-stripped no-m" id="dataTables">
      <thead>
        <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title_en) %></th>
      <th><%= model_class.human_attribute_name(:title_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.title_en %></td>
        <td><%= category.title_id %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>




<script type="text/javascript">
$(document).ready( function () {
$('#dataTables').DataTable();
} );
</script>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<h2>Create New <b><%=t '.title', :default => ['%{model}'], :model => model_class.model_name.human.titleize %></b>  </h2>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<section class="vh25">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h1> <span style="color:#173958">Category</span>  <span style="color:#1980cf"><%= @category.title_id %></span></h1>
        <div class="mt-4">
          <div class="card-columns">
            <% Article.where(category_id: @category.id).order(created_at: :desc).each do |x| %>

              <div class="card">
                <img src="<%= x.image %>" class="card-img-top w-100" alt="..." >
                <div class="card-body">
                  <h5 class="card-title"><%= x.title_id %></h5>
                  <p class="card-text"><%=  ActionView::Base.full_sanitizer.sanitize(x.content_id).truncate(100) %></p>
                  <a href="<%= article_path(x.id) %>" class="btn btn-primary">READMORE</a>
                </div>
              </div>

            <% end %>
          </div>

        </div>
      </div>
      <div class="col-md-3">
        <h3 style="color:#173958">Top Stories</h3>
        <ol class=" series pl-3">
          <% Article.all.order('random()').limit(5).each do |x|%>
          <li><a href="<%= article_path(x.id)%>"><%= x.title_id %></a> </li>
          <% end %>
        </ol>

        <hr>

        <h3 style="color:#173958">Categories</h3>
        <ol class=" series pl-3">
          <% Category.all.each do |x|%>
          <li><a href="<%= category_path(x.id) %>"><%= x.title_id %></a> </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</section>